spring:
  datasource:
    url: jdbc:mysql://192.168.1.35:3306/user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379
