name: CI CD Test Server

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # OpenJDK 배포판

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew  # 실행 권한 부여

      - name: Build and Push Image with Jib
        run: |
          ./gradlew jib \
            -Djib.to.image=docker-repo.minq.work/my-app:latest \
            -Djib.to.auth.username=${{ secrets.REGISTRY_USER }} \
            -Djib.to.auth.password=${{ secrets.REGISTRY_PASSWORD }} \
            --stacktrace --info --no-daemon

      - name: Push JSON to another repository
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: 'data/json'
          destination-github-username: 'MinQDU'
          destination-repository-name: 'spring-database'
          target-branch: main
          target-directory: 'apps/spring-database/server/error'
          user-email: '2024513@daelim.ac.kr'
          user-name: 'GitHub Action Bot'
          commit-message: 'Update internal_error_code.json'