name: CI CD Test Server

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build and Push Image with Jib
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          ./gradlew jib
      - name: Deploy to Docker Swarm
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} daelim@minq.work -p 9981 \
          "docker stack deploy -c docker-compose.yml my-app"